modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
modId="knightcore"
version="1.18.2-1.1"
displayName="Knightcore"
# logoFile="examplemod.png" #optional
credits="Thanks to Melissa, to Forge, to the open-source community, and to the trans community." #optional
authors="MK" #optional
description='''Knightcore is a library dependency for mods created by MK.'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.knightcore]] #optional
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.knightcore]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
